### ISSUE TITLE
use BiocSingular as your PCA/SVD backend

### ISSUE THREAD

**Issue by LTLA** [kevinblighe/PCAtools#1]
Surfing around Github for fun on the weekend (as one does) and spotted this repo.

You might want to consider using [_BiocSingular_](https://bioconductor.org/packages/release/bioc/html/BiocSingular.html) as your backend function for doing PCA/SVDs. This would give you access to fast approximate PCA methods, which would allow you to extend the utility of your package to very large data sets.

Currently, it would literally involve replacing your `prcomp` calls with `runPCA`, though the calculation of proportion of variance explained requires some extra effort to get right when only requesting the top `k` PCs. The approximate methods would also require some limits to the number of extracted PCs, which you might consider adding as an option to your functions.

**Comment by kevinblighe** [comment]
Thanks Aaron - _BiocSingular_ looks interesting. I had wondered (during _PCAtools_ development) which PCA implementation to use, as there are a few available in R.
The package was released just now (May 3) with Bioc 3.9, so, there's plenty of time to address this until Bioc 3.10. I will leave this issue open and get back to this.

**Comment by kevinblighe** [comment]
Addressed in https://github.com/kevinblighe/PCAtools/pull/6
