### ISSUE TITLE
variance miscalculation when setting scale =TRUE 

### ISSUE THREAD

**Issue by taojinsheng** [kevinblighe/PCAtools#11]
Hi Kevin,

PCAtools package is a very fancy tool for high dimension data exploration.However, I found when setting scale=T,the variance for PCs in biplot or pairsplot were wrong.Did you compare the variances between PCAtools and prcomp when scale=T?

Best,

Jinsheng

**Comment by kevinblighe** [comment]
Hey Jinsheng, thank you for your kind comments and for pointing me to this issue.

Can you elaborate what you mean by '_wrong_'? - it should be expected, for example, that variance will change based on whether `scale=TRUE` or `scale=FALSE`

Also, which version of _PCAtools_ are you using? In the official release (v1.0.0), `prcomp()` is used; however, there has already been a change in the development version: now, `BiocSingular::runPCA()` is used to conduct PCA via single value decomposition (https://bioconductor.org/packages/release/bioc/html/BiocSingular.html).

**Comment by taojinsheng** [comment]
Hi Kevin,

Thank you for your prompt reply.My version is PCAtools_1.1.3,from the source code,I knew  BiocSingular::runPCA() is used to conduct PCA. Please find encolsed the data and PCA plot with PCAtools as well as prcomp.Thanks a lot!

Best,
Jinsheng
[PCA data.txt](https://github.com/kevinblighe/PCAtools/files/3499768/PCA.data.txt)
![PCAtools biplot scale as F](https://user-images.githubusercontent.com/23255364/62993938-1ba4e100-be8c-11e9-9683-93041daa937c.png)
![PCAtools biplot scale as T](https://user-images.githubusercontent.com/23255364/62993942-1cd60e00-be8c-11e9-8ee6-e73ea8052beb.png)
![prcomp scale as F](https://user-images.githubusercontent.com/23255364/62993944-1e9fd180-be8c-11e9-965b-43b89703905c.png)
![prcomp scale as T](https://user-images.githubusercontent.com/23255364/62993945-1f386800-be8c-11e9-886c-ecd99f829e58.png)

**Comment by LTLA** [comment]
Usually, it is good etiquette to provide a minimum reproducible example when reporting a bug. Indeed, the data you supplied has `NA`s in it, so it's a wonder that anything works at all.

**Comment by taojinsheng** [comment]
Hi Aaron,

Thanks for your reminding me.Please find enclosed the code and metadata which are required to reproduce my above plots with PCAtools.


[data.zip](https://github.com/kevinblighe/PCAtools/files/3502334/data.zip)


Best,
Jinsheng

**Comment by LTLA** [comment]
The likely cause is a regression at https://github.com/kevinblighe/PCAtools/blob/cfff161950b4169bd8bb331f9635e7801134db19/R/pca.R#L56 which should be `length(vars)` when `scale=TRUE`.

FYI, the code you've supplied doesn't tell me how you created the plots. A true MRE should allow someone to `source` the file and obtain the described results without further modification. For example, https://support.bioconductor.org/p/121323/.

**Comment by taojinsheng** [comment]
Hi, Aaron,

Thank you for your solution and your suggestion about MRE!

Best,
Jinsheng

**Comment by kevinblighe** [comment]
Thanks very much for identifying this, Jinsheng, and thanks Aaron for the quick fix!  I confirm that this now works AOK:

```
require(PCAtools)
mat <- matrix(rexp(200, rate=.1), ncol=20)
```

scale = FALSE:
```
pca(mat, center = TRUE, scale = FALSE)$variance
      PC1       PC2       PC3       PC4       PC5       PC6       PC7       PC8 
26.395486 20.883119 15.503841 10.525045  8.355753  8.122373  4.139871  2.844342 
      PC9      PC10 
 1.809872  1.420297 

p <- prcomp(t(mat), center = TRUE, scale = FALSE)
((p$sdev^2) / (sum(p$sdev^2)))*100
 [1] 26.395486 20.883119 15.503841 10.525045  8.355753  8.122373  4.139871
 [8]  2.844342  1.809872  1.420297
```

scale = TRUE:
```
pca(mat, center = TRUE, scale = TRUE)$variance
      PC1       PC2       PC3       PC4       PC5       PC6       PC7       PC8 
22.499927 18.436944 15.444649 11.777031 10.109787  9.472084  4.404812  3.440984 
      PC9      PC10 
 2.593239  1.820543 
p <- prcomp(t(mat), center = TRUE, scale = TRUE)
((p$sdev^2) / (sum(p$sdev^2)))*100
```

**Comment by taojinsheng** [comment]
Great!Thank all of you for your help.
