### ISSUE TITLE
Method for choosing optimal number of PCA

### ISSUE THREAD

**Issue by kvittingseerup** [kevinblighe/PCAtools#13]
Have you seen Seurat's JackStraw approach (illustrated in this [vignette](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html)) - sounds like an interesting approach as well.

**Comment by kevinblighe** [comment]
Hey Kristoffer, that seems quite useful indeed. Thanks - I will explore how best to implement it in _PCAtools_

**Comment by LTLA** [comment]
Yes, I had a look at it when I first heard about it a few years ago. I recall that it was a repurposing of the original jackstraw method, which is designed to detect significant associations between a gene and a PC. I think the Seurat folks were using it to choose PCs based on whether a particular PC had a uniform-looking distribution of p-values across all genes... for some arbitrary definition of "uniform enough", which of course is where all the fun happens.

From a compute perspective, it's easy enough but you'd have to do more permutations than Horn's PA to get granular p-values. Modest speed-ups are possible by hot-starting the PCA from where the last iteration left off but that's really only possible for IRLBA.

**Comment by kevinblighe** [comment]
Not implementing due to lack of resources. My apologies.
