### ISSUE TITLE
More simple/alternative docs required

### ISSUE THREAD

**Issue by lokapal** [kevinblighe/PCAtools#14]
Hello, Kevin!

It's not an issue, it's rather request to add to this package more SIMPLE example of data loading. E.g. from counts.txt produced by featureCounts, or smth. alike. How to create two/three/four/etc  groups from the columns in this file? How to obtain "classic" PCA plots when two/three/four/etc groups are displayed simultaneously? Thanks in advance!

**Comment by kevinblighe** [comment]
Hey, oh, you mean, like, creating metadata? It's expected, obviously, that the input data will have been at least normalised. Can you elaborate on what you mean by 'classic'?

**Comment by kevinblighe** [comment]
Closed as no response (?). Please re-open if you wish. Kind regards, Kevin
