### ISSUE TITLE
option to plot confidence cicrles

### ISSUE THREAD

**Issue by guidohooiveld** [kevinblighe/PCAtools#19]
Hi,
I really like the functionality `PCAtools` provides, so for me there is not really a need to change to another packages, except that it would be very useful if confidence circles could be plotted. Therefore I kindly would like to put forward a feature request: the option to plot confidence circles on the bi-plot.
An example code can be found here (I lack the R skills to implement it myselves):
https://github.com/federicomarini/pcaExplorer/blob/master/R/pcaplot.R#L63
Thanks for considering!
Guido

**Comment by kevinblighe** [comment]
Hi Guido, thanks! I will take a look at it

**Comment by kevinblighe** [comment]
Hi @guidohooiveld , I have now added this functionality and added you to Acknowledgements.

Let me know what you think: https://github.com/kevinblighe/PCAtools#stat-ellipses

**Comment by guidohooiveld** [comment]
Hi Kevin,
Thanks for implementing the `encircle` option; much appreciated! I updated to the latest version available through GitHub (2.1.12) and it is working nicely.

One question, though (since it is not clear to me): how is the color of the encircled region determined/set? I am asking because (for example) when looking at your [example code](https://github.com/kevinblighe/PCAtools#stat-ellipses) the color of both groups are set (by `colkey`) to `forestgreen` and `purple`, but the color of the encircled region is blue-ish resp. pink. I would have expected the same colors would be used as those defined by `colkey`. I checked it is not an 'optical illusion' due to the setting `ellipseAlpha` (if set to 0.95 it becomes clear that the colors are indeed different than those set by `colkey`).

Thanks!
Guido

**Comment by kevinblighe** [comment]
Hey @guidohooiveld , thank you for spotting that - it seems to _not_ actually pick up the colour specified by `colKey`. I will have to modify this. Perhaps allowing the user to choose colours is the best approach.

**Comment by guidohooiveld** [comment]
Hi, I did some debugging, and it *seems* it is quite simple to solve...
When running step-by-step (part of) the code for the `biplot()` function, I found that just adding a line after the part where `geom_encircle()` [part in lines 387-395] and `stat_ellipse() `[lines 411-421] are called, does the trick.

Line to be added: **`+        scale_fill_manual(values=colkey)`**

Thus:
```
      plot <- plot +
        geom_encircle(
          aes(group = col,
            fill = col,
            colour = col),
          alpha = encircleAlpha,
          size = encircleLineSize,
          show.legend = FALSE,
          na.rm = TRUE) +
          scale_fill_manual(values=colkey)
```

and 

```
      plot <- plot +
        stat_ellipse(
          aes(group = col,
            fill = col),
          colour = 'black',
          geom = 'polygon',
          level = ellipseConf,
          alpha = ellipseAlpha,
          size = ellipseLineSize,
          show.legend = FALSE,
          na.rm = TRUE) +
          scale_fill_manual(values=colkey)
```

Adding this line should be conditional, thus only when` colkey` exists. (if / else). I am sorry, but I don't know (yet) how to efficiently code this within a function. 

Thus (`plot` was generated as per lines 150-175; then):
```

    #lines 178-180
    pp <- plot + scale_colour_discrete('') +
      scale_color_manual(values = colkey)

    #lines 411-421 + added line
    pp2 <- pp +
        stat_ellipse(
          aes(group = col, fill = col),
          colour = 'black',
          geom = 'polygon',
          level = ellipseConf,
          alpha = ellipseAlpha,
          size = ellipseLineSize,
          show.legend = FALSE,
          na.rm = TRUE)  +
          scale_fill_manual(values=colkey)
```

... gives...:

![image](https://user-images.githubusercontent.com/22979991/86177303-adf6b780-bb26-11ea-9cae-530ddd52c7f8.png)


which is the way I would have expected it to be colored when specifying `colkey`.

Idem for` encircle`:

```
      pp3 <- pp +
        geom_encircle(
          aes(group = col,
            fill = col,
            colour = col),
          alpha = encircleAlpha,
          size = encircleLineSize,
          show.legend = FALSE,
          na.rm = TRUE)  +
          scale_fill_manual(values=colkey)

```
![image](https://user-images.githubusercontent.com/22979991/86177664-5278f980-bb27-11ea-8f95-bde84d2fce25.png)

**Comment by kevinblighe** [comment]
Hey @guidohooiveld -  thanks very much for checking that! I will do some testing when I have time. Your suggestion seems to solve the problem though.
As you are also seeing, with these packages, it is possible to simply 'add on' new features via the standard _ggplot2_ functionality.

**Comment by kevinblighe** [comment]
Hey @guidohooiveld , this should now be working. I have also added parameters that allow one to supply custom colours to the ellipses / 'encircle' lines. When using custom colours, `[ellipse|encircle]LineSize` should be 0 to remove the original border. New examples are in the vignette.

Thanks!

**Comment by guidohooiveld** [comment]
Thanks @kevinblighe !
However, somehow I can't get the latest dev version installed (on Windows).

```
> devtools::install_github('kevinblighe/PCAtools')
Downloading GitHub repo kevinblighe/PCAtools@master
 checking for file 'C:\TMP_R\RtmpsdGOP2\remotes399c9457cd8\kevinblighe-PCAtools-0c44f1b/DESCRIPTION' ...

 checking for file 'C:\TMP_R\RtmpsdGOP2\remotes399c9457cd8\kevinblighe-PCAtools-0c44f1b/DESCRIPTION' ... 
√  checking for file 'C:\TMP_R\RtmpsdGOP2\remotes399c9457cd8\kevinblighe-PCAtools-0c44f1b/DESCRIPTION' (544ms)

  
  
  
-  preparing 'PCAtools':
   checking DESCRIPTION meta-information ...
  
   
   checking DESCRIPTION meta-information ... 
  

√  checking DESCRIPTION meta-information
-  cleaning src

  
Warning:
  
   Warning: newline within quoted string at biplot.rd:63
   Warning: C:/TMP_R/RtmpCUNokm/Rbuild44cc26ee1d91/PCAtools/man/biplot.rd:213: unknown macro '\item'
   Warning: newline within quoted string at biplot.rd:63
   Warning: C:/TMP_R/RtmpCUNokm/Rbuild44cc26ee1d91/PCAtools/man/biplot.rd:214: unknown macro '\item'
   Warning: newline within quoted string at biplot.rd:63
   Warning: C:/TMP_R/RtmpCUNokm/Rbuild44cc26ee1d91/PCAtools/man/biplot.rd:216: unknown macro '\item'

<<snip>>

C:/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o PCAtools.dll tmp.def RcppExports.o shuffle_matrix.o -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Program Files/R/R-4.0.2/library/00LOCK-PCAtools/00new/PCAtools/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) newline within quoted string at biplot.rd:63
ERROR: installing Rd objects failed for package 'PCAtools'
* removing 'C:/Program Files/R/R-4.0.2/library/PCAtools'
Error: Failed to install 'PCAtools' from GitHub:
  (converted from warning) installation of package ‘C:/TMP_R/RtmpsdGOP2/file399c16782133/PCAtools_2.1.14.tar.gz’ had non-zero exit status
> 

```

**Comment by kevinblighe** [comment]
Hmm, that is strange. Let me take a look at it today. Could be a new issue related to R version >4.0.0

**Comment by kevinblighe** [comment]
Hey @guidohooiveld , can you check again now?

**Comment by guidohooiveld** [comment]
@kevinblighe : Yes, installing and working fine now.
Thanks a lot!

**Comment by kevinblighe** [comment]
Great - thank you for your help @guidohooiveld ! You are in the ACKs

**Comment by kevinblighe** [comment]
Hey @guidohooiveld , thanks again for your contribution. I felt that it was enough to merit a 'contributor' (ctb) status, which you can now see in the Devel branch on Bioconductor: http://www.bioconductor.org/packages/devel/bioc/html/PCAtools.html

**Comment by guidohooiveld** [comment]
Thanks! Not needed, but much appreciated! 👍
