### ISSUE TITLE
custom labels for the points

### ISSUE THREAD

**Issue by alfonsosaera** [kevinblighe/PCAtools#2]
Hi @kevinblighe,

very nice and complete package, thanks for developing it.

Is there a way of using customized labels? I mean supplying a vector or a metadata dataframe column to be used as labels. This would be useful when the sample names start with a number (1.hour, 2.hours ...) for example since R adds an X to column name.

Thanks,

Alfonso

**Comment by kevinblighe** [comment]
Hey Alfonso, thank you for using _PCAtools_. No, there is, currently, no way to use a custom sample name. _PCAtools_ will take whatever information is contained in the metadata object. Could you use hour 1; hour 2, etc?

I will leave this issue open so that I can add this feature eventually.

**Comment by kevinblighe** [comment]
This feature is now implemented in the development branch. You can now simply pass any vector to the `lab` parameter for the labels. Please reply back here if you wish to be added to the acknowledgements.

**Comment by alfonsosaera** [comment]
Hi @kevinblighe,

Thanks for adding this feature, there is no need of adding me to the acknowledgements :-)
