### ISSUE TITLE
reading object of class phyl.pca ?

### ISSUE THREAD

**Issue by Jigyasa3** [kevinblighe/PCAtools#23]
I wanted to ask if it's possible to load object of class phyl.pca instead of pca?

**Comment by kevinblighe** [comment]
Hey @Jigyasa3 , I have not used _phyl.pca_ previously. Can you provide a typical use-case?

I looked briefly and can see that _phyl.pca_ returns an object with the key objects required by _PCAtools_; so, you could attempt to create a 'minimalist' object like this:

```
# create a new object
pcaobj <- list(
  rotated = data.frame(phyl.pca$Evec),
  loadings = data.frame(phyl.pca$L),
  variance = NULL,
  sdev = NULL,
  metadata = NULL,
  xvars = NULL,
  yvars = NULL,
  components = colnames(phyl.pca$Evec))

# assign class pca to object
class(pcaobj) <- 'pca'
```
However, the functionality of this with the other _PCAtools_ functions is unknown. For example, `variance `is used by many functions, as are the `xvars `and `yvars`.

**Comment by kevinblighe** [comment]
Hi @Jigyasa3 , have you tried anything new since posting this issue?

**Comment by Jigyasa3** [comment]
Hey @kevinblighe 

Thank you so much for replying to my message!
Sorry for not replying earlier. I was able to find the flexibility that I was looking for in another R package called Compositions.


Thank you so much for being so prompt in replying!

**Comment by kevinblighe** [comment]
Sounds great - thanks for getting back.
