### ISSUE TITLE
Analysis of RNAseq data with cases and controls

### ISSUE THREAD

**Issue by javanOkendo** [kevinblighe/PCAtools#24]
Hi Kevin,

I have the count matrix of RNAseq data with cases and controls and I would like to use this package in the analysis. Do you have an example workflow on how to do that? Or if you can show me how to prepare that data because I tried to follow the example but it was not successful. Kindly let me know if you do have one

**Comment by kevinblighe** [comment]
Hi, your input to _PCAtools_ should be the transformed expression levels. I cannot comment further because you have not said anything about which program that you are using. You may consider posting this question on Biostars, but please provide further information about which program(s) you are using.

Kind regards,
Kevin

**Comment by kevinblighe** [comment]
I will aim to add to vignette.

**Comment by javanOkendo** [comment]
@kevinblighe I used the[ nf-core pipeline](https://www.nature.com/articles/s41587-020-0439-x) which basically runs on nextflow to generate the  the count matrix. I used the Deseq2 bio-conductor for the downstream analysis.  
I have done all the differential analysis and the heatmap visualization and I think PCAtools will be helpful in understanding the genes driving variations in my data. PCAtools will also help me in squeezing my data further to gain more insight. I hope this now makes more sense.

**Comment by kevinblighe** [comment]
Oh I see - thanks!  If you are using DESeq2, then you just need the original metadata and the variance-stabilised or regularised log expression levels (as input to PCAtools). Do you have those?

**Comment by javanOkendo** [comment]
I was thinking if you can adjust the PCA plots to have legends on the sides like this. Instead of the sample names
![image](https://user-images.githubusercontent.com/26459707/85293397-8dcb5680-b49d-11ea-96de-6075034ac034.png)

**Comment by javanOkendo** [comment]
@kevinblighe or there is we can switch off the names in this plot? just to have the color codes to represent the patients and the sample groups

![image](https://user-images.githubusercontent.com/26459707/85293838-311c6b80-b49e-11ea-9f16-bcaf053d0ead.png)

**Comment by kevinblighe** [comment]
Sure, just use `lab = NULL`.

For legend configuration, you can use:
```
legendPosition
legendLabSize
legendIconSize
```

**Comment by kevinblighe** [comment]
Please re-open this issue if you need further help?

**Comment by javanOkendo** [comment]
Well I have another issue that is not related to PCAtools and i hope you can help in this regard. I am trying to follow the clusterProfiler in the analysis of Gene Ontology but I am not able to make the geneList file. I have differential analysis results, can I share part of it with you if you can help in making this gene list file.
