### ISSUE TITLE
biplot loading arrows error

### ISSUE THREAD

**Issue by TonyMannion** [kevinblighe/PCAtools#25]
Hi,

I am following the example to make a biplot with the loadings, but seems to have an error...

>   biplot(p, showLoadings = TRUE, lab = NULL)
Error in biplot(p, showLoadings = TRUE, lab = NULL) : 
  unused argument (showLoadings = TRUE)

**Comment by kevinblighe** [comment]
Hey, thanks for using this package. To avail of that new functionality, you'll have to install the GitHub version via:

`devtools::install_github('kevinblighe/PCAtools')
`
...or

`remotes::install_github('kevinblighe/PCAtools')
`

The functionality will only be available via `install.packages()` or `BiocManager::install()` when the next version of Bioconductor is released.

**Comment by kevinblighe** [comment]
Let me know if that solves it for now, and please re-open this issue if not.

Kind regards,
Kevin
