### ISSUE TITLE
Error with ellipse feature

### ISSUE THREAD

**Issue by amarinderthind** [kevinblighe/PCAtools#27]
Hi Kevin,

I am getting the following error while plotting PCA with the eclipse feature, otherwise, it is working fine.

Error in biplot(p, colby =.........................  unused argument (ellipse = TRUE)

I updated my package, still, can't find this feature (after taking look on help)

**Comment by kevinblighe** [comment]
Hey, you just need to install the development version, or the GitHub version. Please see here: https://github.com/kevinblighe/PCAtools/issues/26

Thanks and kind regards,
Kevin
