### ISSUE TITLE
An eigencor plot?

### ISSUE THREAD

**Issue by hamidghaedi** [kevinblighe/PCAtools#28]
Hi Kevin and other valued developers,

Does astricts in eigencor  plot mean significant correlation? What about the statistic printed in cells of eigencor plot?
I would appreciate it if you elaborate on that a bit.
Thanks

**Comment by kevinblighe** [comment]
Hey!

The asterisks relate to significancies, as per the following parameters:

```
signifSymbols | Statistical significance symbols to display beside correlation values. DEFAULT = c('***', '**', '*', ”). OPTIONAL.
signifCutpoints | Cut-points for statistical significance. DEFAULT = c(0, 0.001, 0.01, 0.05, 1). OPTIONAL
```

The p-values for these are derived from the correlation test via `cor.test()`, and these [p-values] can be adjusted, as per:

`corMultipleTestCorrection | Multiple testing p-value adjustment method. Any method from stats::p.adjust() can be used. Activating this function means that signifSymbols and signifCutpoints then relate to adjusted (not nominal) p-values. DEFAULT = 'none'.
`

The numbers in the plot relate to the correlation coefficients. parameters controlling these include:


```
corFUN | Correlation method: 'pearson', 'spearman', or 'kendall'. DEFAULT = 'pearson'. OPTIONAL.
corUSE | Method for handling missing values (see documentation for cor function via ?cor). 'everything', 'all.obs', 'complete.obs', 'na.or.complete', or 'pairwise.complete.obs'. DEFAULT = 'pairwise.complete.obs'. OPTIONAL.
```

Kevin
