### ISSUE TITLE
difference between PCA with and witout metadata

### ISSUE THREAD

**Issue by Manonanthini** [kevinblighe/PCAtools#30]
Hi Kevin,
Thanks for the package.
I am a beginner. I would like to know two things i need
1. If i run PCA for gene expression with metadata (Age,BMI,Sex etc.), shall i consider like i have adjusted the expression data with these covariates?
2. If I want to get the correlated PCA object in eigencorplot(),is there any other way other than plotting. Please reply.
Thanks in advance.

**Comment by kevinblighe** [comment]
Hi, thanks for using this package. Let me answer your questions:

"_If i run PCA for gene expression with metadata (Age,BMI,Sex etc.), shall i consider like i have adjusted the expression data with these covariates?_"

No, _PCAtools_ performs no adjustment for any covariates.


"_If I want to get the correlated PCA object in eigencorplot(),is there any other way other than plotting. Please reply.
Thanks in advance._"

To obtain the actual correlation values, you just need to perform a standard correlation between `pcaobj$rotated` and `pcaobj$metadata`.
