### ISSUE TITLE
Setting scale=TRUE produced error from svd()

### ISSUE THREAD

**Issue by chainorato** [kevinblighe/PCAtools#39]
Hi, Thank you very much for developing this package.

I have just set up PCAtools today and I tried to make a PCA plot of expression profiles (transformed by `vst` function in DESeq2) by the following code.

```
vsd <- assay(vst(dds, blind=TRUE))
p <- pca(vsd, metadata=samples, center=TRUE, scale=FALSE)
biplot(p, colby="condition", shape="condition", labSize = 0, pointSize = 6)
```

It smoothly produced the following nice plot.

![Screen Shot 2021-05-19 at 0 16 48](https://user-images.githubusercontent.com/32287948/118678077-ab34ac00-b837-11eb-98bb-50a34680aaa2.png)

However, when I set the scale parameter to TRUE for standardization.
`p <- pca(vsd, metadata=samples, center=TRUE, scale=TRUE)`

There is an error.

> Error in svd(x, nu = nu, nv = nv) : infinite or missing values in 'x'

The documentation (`?svd`) states that it is a numeric or complex matrix whose SVD decomposition is to be computed.
However, I could not understand how infinite or missing values popped up in 'x' which I am unsure which matrix it is.

My questions are
1.  It seems that data points already vary around (0,0). Does this mean they are already scaled by DESeq vst() function?
2. If the parameter scale also has to be set as TRUE, could you please help me figure out what is wrong here? Could I send you the data through email if it is necessary?

**Comment by kevinblighe** [comment]
Hi, scaling variance-stabilised data from _DESeq2_ should not be necessary for PCA. However, if you simple try t(scale(t(vsd))), does it produce an error? Have you pre-filtered your raw counts for genes with 0 counts across all samples?

**Comment by kevinblighe** [comment]
Cool, so, the issue was related to genes of constant variance, i.e., all zeros.
I don't think that scaling the data is necessary when coming via the DESeq2::vst() route. If the data was more 'difficult', like, e.g., proteomics data, then I would scale it. It is a question with no real concrete answer, though. It may have been asked afew times before on, e.g., StackExchange.
Please re-open the issue if problems still occur!
