### ISSUE TITLE
Implement Selection of Rows in pca() function

### ISSUE THREAD

**Issue by groverj3** [kevinblighe/PCAtools#4]
Thanks for making such a nice package. Since I stumbled across it from your Biostars posts it's been really helpful in simplifying my workflow and teaching others in our lab about PCA.

A small feature you might consider for future releases would be to implement a way to subset the rows on which the pca() function is fun. That way, users could compare the effect of subsetting on their PCs. For example, what effect does subsetting the most variable 10%, 25%, 50% of the rows (genes, or whatever people are testing) have on the output?

It's not very hard to do this before feeding the data into the function, but it would probably help less experienced R users.

Thanks!

**Comment by kevinblighe** [comment]
Hey, thank you for the comments and apologies for the delay. I am only now getting around to catching up on edits to this package.

Do you mean performing a sort of cross validation of the PCA?; so, dividing the dataset into 'random' chunks and then performing the PCA on each? If so, that is a great idea but will involve some concentrated dev. time.

**Comment by groverj3** [comment]
Oh, nothing so complicated. I was explaining to another user recently how DESeq2's built-in PCA function only uses genes with the highest variation (I forget how many, maybe 500?), and how it might be good to check how things look with the full dataset or other sized subsets. So implementing an option to specify how many rows of the input dataframe you want to use might be useful.

But, what you mentioned would also be a really appealing option. Surely it would be more work though.

Thanks for the reply!

**Comment by kevinblighe** [comment]
Yes, _DESeq2_'s `plotPCA()` pre-selects the top _n_ most highly variable genes, which somewhat biases the PCA analysis. For _PCAtools_'s `pca()` function, there is a parameter called `removeVar`, which allows you to remove a lower proportion of variables based on variance; however, the default value is `NULL`.

The other idea, if done with enough bootstraps or some form of 'leave one out' cross validation would ultimately allow the user to identify the key genes that comprise the 'glue' of the bi-plots (I think).

**Comment by groverj3** [comment]
Oh, I did not realize that was already an option. I guess I need to read the documentation again!

The validation idea is definitely interesting, I don't know of a package that does that sort of thing.

I'll close this issue because apparently it's already been implemented but I'll keep an eye on development.

**Comment by kevinblighe** [comment]
Sure thing! - thanks for using the package!
