### ISSUE TITLE
exporting results for interactive visualization?

### ISSUE THREAD

**Issue by guidohooiveld** [kevinblighe/PCAtools#40]
Hi Kevin,
This has nothing directly to do with the functionality of `PCAtools` and maybe out of scope, yet I still would like to ask:
Considering your extensive know-how on PCA and data visualization, I was wondering whether you have any experience on exporting results/plots from `PCAtools` for (semi-) interactive visualization in 3D plot in e.g. HTML format or so. So results of analyses can be easily shared with a collaborator (biologist) for her/him to 'play with'. Any suggestion or pointer would be appreciated.
Thanks,
Guido

**Comment by kevinblighe** [comment]
Hey Guido,

Hmm, the data can be easily exported, preferably the `loadings` and `rotated` objects (see https://github.com/kevinblighe/PCAtools/blob/master/R/pca.R#L169-L178) and then used by your collaborator.

An alternative may be via _crosstalk_, as is shown here for _EnhancedVolcano_: https://www.biostars.org/p/421750/#421769
There may even be a way to share a web-link via _crosstalk_, but I am not sure.

Another option, of course, is via RShiny or RStudio server.

Kind regards,
Kevin

**Comment by guidohooiveld** [comment]
Hi,
Thanks a lot for these suggestions. I will explore them, and report back.
G

**Comment by kevinblighe** [comment]
Great, thanks @guidohooiveld
