### ISSUE TITLE
Use other metadata than "colby" for encircle 

### ISSUE THREAD

**Issue by SebastianHesse** [kevinblighe/PCAtools#46]
Hi,
is there a way I could use other metadata than the one defined by "colby" for encircle?
In my specific case, I want to use colby for the genotype and use encirlce to show cluster assignment.
It seems that I can only use the attribute chosen by colby and encircling them is a bit redundant. Would be very cool if instead I could show another layer of metadata with encircle. 
Thanks a lot!
Sebastian

**Comment by kevinblighe** [comment]
Hi! There is not yet any way to do this. It could be coded, but, unfortunately, my time is extremely limited, and I therefore have no estimate as to when this could be done.
