### ISSUE TITLE
can't hide ellipseline

### ISSUE THREAD

**Issue by little2b** [kevinblighe/PCAtools#47]
I have set ellipseLineSize = 0,but there is still ellipseline in my picture.
![image](https://user-images.githubusercontent.com/91416398/140933153-0b26144b-9e16-4278-bb04-03e0f4ab9b08.png)

**Comment by kevinblighe** [comment]
Can you please show the code that you are running.

**Comment by little2b** [comment]
this is my code:
```
biplot(p,
       x='PC1',
       y = 'PC2',
       labSize = 0.25,
       pointSize = 1,
       colby = 'group',colkey = c('Tumor'='forestgreen','Normal'='red'),
        ellipse = TRUE,
        ellipseType = 't',
        ellipseLevel = 0.95,
        ellipseFill = TRUE,
        ellipseAlpha = 1/4,
        ellipseLineSize = 0,
        ellipseFillKey = c('Tumor'='yellow','Normal'='pink'),
       legendPosition = 'top')
```

**Comment by kevinblighe** [comment]
Thank you. Have you gone through the vignette to see if it works from there?

**Comment by little2b** [comment]
yes it like this
![image](https://user-images.githubusercontent.com/91416398/141456368-feee9f7d-dc6c-4af3-a918-1272ddcfd5e1.png)
but i want ellipse line is hidden, and i set a code:`ellipseLineSize = 0`
but it is still exist

**Comment by kevinblighe** [comment]
No, please run the vignette code. The function works there. Please see the second plot from here: https://github.com/kevinblighe/PCAtools#stat-ellipses

**Comment by little2b** [comment]
I coped your code for the second plot and ran it:
```
biplot(p,
       colby = 'group', colkey = c('Tumor'='forestgreen','Normal'='purple'),
       # ellipse config
       ellipse = TRUE,
       ellipseType = 't',
       ellipseLevel = 0.95,
       ellipseFill = TRUE,
       ellipseAlpha = 1/4,
       ellipseLineSize = 0,
       ellipseFillKey = c('Tumor' = 'yellow', 'Normal' = 'pink'),
       xlim = c(-125,125), ylim = c(-50, 80),
       hline = 0, vline = c(-25, 0, 25),
       legendPosition = 'top', legendLabSize = 16, legendIconSize = 8.0)
```
but the line is still here
![image](https://user-images.githubusercontent.com/91416398/141459203-255b7ff7-f638-405b-817e-62e713f5e2a3.png)

**Comment by kevinblighe** [comment]
That is not quite what I meant. Please run the vignette code, from start to finish, and let me know if that works.

**Comment by little2b** [comment]
I'm very sorry for causing you trouble, but what is the vignette code.

**Comment by kevinblighe** [comment]
Ah, my apologies! It just means can you run the code, starting from here: https://github.com/kevinblighe/PCAtools#2-load-the-package-into-r-session

Then, when you get to the part with `ellipseLineSize`, how does it work?
