### ISSUE TITLE
Support PCA methods for `base` based `pca`

### ISSUE THREAD

**Issue by Nelson-Gon** [kevinblighe/PCAtools#50]
Hello,

Awesome package. I was wondering if it could be possible to enable `base` support for most of the functionality in the package. 

For example, given `mtcars`

```
mt_pca <-prcomp(mtcars, scale =F, center = T)
PCAtools::getComponents(mt_pca)
NULL
```
(Unrelated but perhaps there should be a warning/error for non implemented objects?)
The reason for this is that I love the package and would like to use some of these functions. However, asserting that the object is a `pcaobj` currently restricts most functionality. 

Thank you,

NelsonGon

**Comment by kevinblighe** [comment]
Hi, this will not be implemented due to lack of funding and resources. You are welcome to submit a PUll Request to enable this, if you wish.

Kevin

**Comment by Nelson-Gon** [comment]
Sorry to hear, I will see if I can PR and add this implementation.

Thank you,

NelsonGon
