### ISSUE TITLE
Changing size of shape legend icons / symbols

### ISSUE THREAD

**Issue by milcs40** [kevinblighe/PCAtools#51]
Hello,

I have been using PCAtools for most of my PCA plotting and think it's amazing! 
I have a very small/simple question. 
When I'm plotting a PCA with metadata corresponding to different conditions (e.g. 'Culture Conditions' and 'Genotype'), and use 

```
biplot(prlog, 
       colby = 'Culture Conditions', 
       shape = "Genotype",
       pointSize = 3,
       legendPosition = 'right',
       legendTitleSize = 12,
       legendLabSize = 10, 
       legendIconSize = 1)
```
I can't seem to be able to change the size of the icons for the shape legend, as 'legendIconSize' is only working for the 'colby' legend.

Am I missing something? Is there a way around this? 
Cheers and thank you again for this amazing tool.

**Comment by kevinblighe** [comment]
Hi, thanks for your comments. To do this, I think that you can simply 'add on' a ggplot2 function to increase the legend sizes, something like that suggested here:
https://www.geeksforgeeks.org/control-size-of-ggplot2-legend-items-in-r/#:~:text=To%20change%20the%20Size%20of,take%20an%20argument%20called%20override.

So, it would be:
`biplot(...) + guides(color = guide_legend(override.aes = list(size = 10)))`
