### ISSUE TITLE
Legend with Pairsplot

### ISSUE THREAD

**Issue by hmraimeryoung-95** [kevinblighe/PCAtools#54]
Hello,

I am using parisplots and created the first attached plot without legends (example_without_legend) using the following code:

`p <- pca(assay(vsd), metadata = col_data)

pairsplot(p, 
          colby = 'group',
          gridlines.major = FALSE, gridlines.minor = FALSE,
          plotaxes = FALSE,
          hline = 0, vline = 0,
          legendPosition = 'none')`

So then I wanted to add a legend to better interpret my data by modifying `legendPosition = 'left'` and produced the second plot (example_with_legend). 

Is there a way to create a legend functionality where a single legend is created, instead of making a legend for each biplot, and then the legend could sit in the white space left from the triangle arrangement?

Thanks
[example_without_legend.pdf](https://github.com/kevinblighe/PCAtools/files/8766052/example_without_legend.pdf)
[example_with_legends.pdf](https://github.com/kevinblighe/PCAtools/files/8766056/example_with_legends.pdf)

**Comment by kevinblighe** [comment]
Hi @hmraimeryoung-95 , yes, this is why I disabled by default the legend functionality in pairs plots.

I have no resources to modify the code right now to help here, so, I may suggest that you generate the legend via the biplot() function and then manually add it to the pairs plot.

Apologies that I cannot offer a better solution for now - I literally have no resources to further develop this packages.
