### ISSUE TITLE
ggpairs plots legend for every subplot

### ISSUE THREAD

**Issue by sparsepix** [kevinblighe/PCAtools#56]
Hi,
I just found another issue. When plotting the pairsplot, the standard setting is no labels. I usually want to use it to see if I have any separation by sample (and then find out what genes are responsible). However when using `colby = 'sample'` and `legendPosition = 'top'` the function plots the legend for every subplot (and of course, there is not enough space to show the labels). Any way to change this behavior, so that only one legend is displayed? 

Best, Niko

**Comment by kevinblighe** [comment]
Hi again Niko, unfortunately there is ni direct solution for this. You may try my suggestion as mentioned here:
https://github.com/kevinblighe/PCAtools/issues/54

Kind regards,
Kevin

**Comment by mdidish** [comment]
Here is a solution to display legend from biplot and display it before drax pairsplot:

```
plot <-  biplot(pca.res,
       colby = "anevrysm.cat",
       legendPosition = 'bottom', legendLabSize = 8, legendIconSize = 4.0)
       
as_ggplot(get_legend(plot))

pairsplot(
  pcaobj = pca.res,
  components = c(1:5),
  colby = "anevrysm.cat",
  triangle = TRUE
)
```
