### ISSUE TITLE
Random matrix theory methods to choose no. of PCs

### ISSUE THREAD

**Issue by LTLA** [kevinblighe/PCAtools#9]
Here's two more methods to choose the number of PCs (stolen from https://github.com/LTLA/PCSelection2018/). They both require:

- The expression matrix `observed`, duh.
- The singular values in `SVD$d`
- The standard deviation of the i.i.d. noise in `sigma`.

```r
# Using the Marchenko-Pastur limit on the _eigenvalues_.
# (See https://www.wolfram.com/language/11/random-matrices/marchenko-pastur-distribution.html?product=mathematica)
# Multiplying the limit by the mean technical component of the variance to account for scaling.
ndf <- nrow(observed) - 1
limit <- RMTstat::qmp(1, ndf=ndf, pdim=ncol(observed)) * sigma^2
marchenko <- sum(SVD$d^2/ndf > limit)
marchenko <- max(1L, marchenko)

# Applying the Gavish-Donoho method, given the noise 'sigma'.
m <- min(dim(observed))
n <- max(dim(observed))
beta <- m/n
lambda <- sqrt( 2 * (beta + 1) + (8 * beta) / ( beta + 1 + sqrt(beta^2 + 14 * beta + 1) ) )
gv <- sum(SVD$d > lambda * sqrt(n) * sigma
gv <- max(1L, gv)
```

**Comment by LTLA** [comment]
Okay, your `help-wanted` thing definitely got my attention.

I can roll these up into some functions but we would need to expose the D vector from `pca()`. Not too hard, in and of itself, but the output of `pca()` is starting to get pretty bloated.

**Comment by kevinblighe** [comment]
Hey, sorry, been busy and working / traveling over the holiday period. I will get back to this eventually...!

**Comment by kevinblighe** [comment]
Hey @LTLA , I have been updating this package again and returned to this. I am just not seeing how I can get SVD$D and sigma (?)  Are they via `BiocSingular::runPCA()`?

**Comment by kevinblighe** [comment]
We could perhaps just include this entire code chunk, and this addresses Kristoffer's comment about including JackStraw ( here: https://github.com/kevinblighe/PCAtools/issues/13 ), too:
https://github.com/LTLA/PCSelection2018/blob/master/simulations/functions.R

**Comment by LTLA** [comment]
`sigma` is a user-supplied value, let's not worry about that. `SVD$d` is the diagonal vector of the SVD, that's what I was wondering whether we could get `pca()` to emit.
